print('Jak masz na imię ?')
my_name= input()
print('Miło Cię poznać' + my_name + '.')
print('Liczba znaków w Twoim imieniu wynosi:')
print(len(my_name))
print('Ile masz lat?')
my_age= input()
print('W przyszłym roku będziesz miał ' + str(int(my_age) + 1) + 'lat.')
print('Z jakiego miasta pochodzisz ?')
my_city= input()
print('Mieszkasz w ' + my_city + '.')